/*
 * LogistiqoAPI
 *   - Go to [Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/habatlogistiqocom/logistiqoSwaggerYaml/main/logistiqoSwaggerYaml.yaml)   An API, or Application Programming Interface, is a set of protocols,   routines, and tools that enable different software applications to   communicate and exchange data with each other. It defines how software   components should interact and helps to simplify software development by   abstracting the underlying implementation. APIs are essential for building   complex and interconnected software systems.       ## Contact Us     If you have problems or questions, please read the following information:     - [FAQ](https://www.logistiqo.com/faq/)    - [Contact us](https://www.logistiqo.com/contact.php)     To stay informed about the latest developments, you can     - Follow us on [Twitter](https://twitter.com/logistiqo/),
 *
 * OpenAPI spec version: 1.0
 * Contact: info@logistiqo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PaymentTerms
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-19T13:45:14.600795045Z[GMT]")

public class PaymentTerms {
  @SerializedName("cashDiscountDays")
  private Integer cashDiscountDays = null;

  @SerializedName("days")
  private Integer days = null;

  @SerializedName("longName")
  private String longName = null;

  @SerializedName("shortName")
  private String shortName = null;

  @SerializedName("cashDiscount")
  private Double cashDiscount = null;

  public PaymentTerms cashDiscountDays(Integer cashDiscountDays) {
    this.cashDiscountDays = cashDiscountDays;
    return this;
  }

   /**
   * Get cashDiscountDays
   * @return cashDiscountDays
  **/
  @Schema(description = "")
  public Integer getCashDiscountDays() {
    return cashDiscountDays;
  }

  public void setCashDiscountDays(Integer cashDiscountDays) {
    this.cashDiscountDays = cashDiscountDays;
  }

  public PaymentTerms days(Integer days) {
    this.days = days;
    return this;
  }

   /**
   * Get days
   * @return days
  **/
  @Schema(description = "")
  public Integer getDays() {
    return days;
  }

  public void setDays(Integer days) {
    this.days = days;
  }

  public PaymentTerms longName(String longName) {
    this.longName = longName;
    return this;
  }

   /**
   * Get longName
   * @return longName
  **/
  @Schema(description = "")
  public String getLongName() {
    return longName;
  }

  public void setLongName(String longName) {
    this.longName = longName;
  }

  public PaymentTerms shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
  @Schema(description = "")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public PaymentTerms cashDiscount(Double cashDiscount) {
    this.cashDiscount = cashDiscount;
    return this;
  }

   /**
   * Get cashDiscount
   * @return cashDiscount
  **/
  @Schema(description = "")
  public Double getCashDiscount() {
    return cashDiscount;
  }

  public void setCashDiscount(Double cashDiscount) {
    this.cashDiscount = cashDiscount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentTerms paymentTerms = (PaymentTerms) o;
    return Objects.equals(this.cashDiscountDays, paymentTerms.cashDiscountDays) &&
        Objects.equals(this.days, paymentTerms.days) &&
        Objects.equals(this.longName, paymentTerms.longName) &&
        Objects.equals(this.shortName, paymentTerms.shortName) &&
        Objects.equals(this.cashDiscount, paymentTerms.cashDiscount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cashDiscountDays, days, longName, shortName, cashDiscount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentTerms {\n");
    
    sb.append("    cashDiscountDays: ").append(toIndentedString(cashDiscountDays)).append("\n");
    sb.append("    days: ").append(toIndentedString(days)).append("\n");
    sb.append("    longName: ").append(toIndentedString(longName)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    cashDiscount: ").append(toIndentedString(cashDiscount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
