/*
 * LogistiqoAPI
 *   - Go to [Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/habatlogistiqocom/logistiqoSwaggerYaml/main/logistiqoSwaggerYaml.yaml)   An API, or Application Programming Interface, is a set of protocols,   routines, and tools that enable different software applications to   communicate and exchange data with each other. It defines how software   components should interact and helps to simplify software development by   abstracting the underlying implementation. APIs are essential for building   complex and interconnected software systems.       ## Contact Us     If you have problems or questions, please read the following information:     - [FAQ](https://www.logistiqo.com/faq/)    - [Contact us](https://www.logistiqo.com/contact.php)     To stay informed about the latest developments, you can     - Follow us on [Twitter](https://twitter.com/logistiqo/),
 *
 * OpenAPI spec version: 1.0
 * Contact: info@logistiqo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * UnitLoadDeviceContent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-21T16:41:44.170656590Z[GMT]")

public class UnitLoadDeviceContent {
  @SerializedName("shipmentNumber")
  private String shipmentNumber = null;

  @SerializedName("customerReference")
  private String customerReference = null;

  @SerializedName("quantity")
  private BigDecimal quantity = null;

  @SerializedName("packlineId")
  private String packlineId = null;

  public UnitLoadDeviceContent shipmentNumber(String shipmentNumber) {
    this.shipmentNumber = shipmentNumber;
    return this;
  }

   /**
   * Get shipmentNumber
   * @return shipmentNumber
  **/
  @Schema(example = "23 00567", description = "")
  public String getShipmentNumber() {
    return shipmentNumber;
  }

  public void setShipmentNumber(String shipmentNumber) {
    this.shipmentNumber = shipmentNumber;
  }

  public UnitLoadDeviceContent customerReference(String customerReference) {
    this.customerReference = customerReference;
    return this;
  }

   /**
   * Get customerReference
   * @return customerReference
  **/
  @Schema(example = "CR67890", description = "")
  public String getCustomerReference() {
    return customerReference;
  }

  public void setCustomerReference(String customerReference) {
    this.customerReference = customerReference;
  }

  public UnitLoadDeviceContent quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * :&gt;- The quantity specifies the number of identical goods items (with the same packlineId) consolidated on a specific Unit Load Device (ULD).
   * @return quantity
  **/
  @Schema(example = "2", description = ":>- The quantity specifies the number of identical goods items (with the same packlineId) consolidated on a specific Unit Load Device (ULD).")
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public UnitLoadDeviceContent packlineId(String packlineId) {
    this.packlineId = packlineId;
    return this;
  }

   /**
   * :&gt;- The packlineId functions as a distinctive identifier for delineating particular sets of goods or items consolidated on a single Unit Load Device (ULD).
   * @return packlineId
  **/
  @Schema(example = "23 00567", description = ":>- The packlineId functions as a distinctive identifier for delineating particular sets of goods or items consolidated on a single Unit Load Device (ULD).")
  public String getPacklineId() {
    return packlineId;
  }

  public void setPacklineId(String packlineId) {
    this.packlineId = packlineId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnitLoadDeviceContent unitLoadDeviceContent = (UnitLoadDeviceContent) o;
    return Objects.equals(this.shipmentNumber, unitLoadDeviceContent.shipmentNumber) &&
        Objects.equals(this.customerReference, unitLoadDeviceContent.customerReference) &&
        Objects.equals(this.quantity, unitLoadDeviceContent.quantity) &&
        Objects.equals(this.packlineId, unitLoadDeviceContent.packlineId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentNumber, customerReference, quantity, packlineId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnitLoadDeviceContent {\n");
    
    sb.append("    shipmentNumber: ").append(toIndentedString(shipmentNumber)).append("\n");
    sb.append("    customerReference: ").append(toIndentedString(customerReference)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    packlineId: ").append(toIndentedString(packlineId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
